version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /meatmeet/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/meatmeet/frontend
    tty: true
    restart: always
    command: sh -c "cd app && yarn start"
